# Generated by Django 6.0.1 on 2026-01-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_department_employee_department_designation_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PF', 'Provident Fund'), ('ESI', 'Employee State Insurance'), ('PT', 'Professional Tax'), ('TDS_SLAB', 'TDS Slab')], max_length=20)),
                ('employee_contribution_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('employer_contribution_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wage_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Salary limit for eligibility', max_digits=10, null=True)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat amount to deduct if applicable', max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_rates', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 2023-2024', max_length=9)),
                ('section_80c', models.DecimalField(decimal_places=2, default=0.0, help_text='LIC, PPF, etc.', max_digits=10)),
                ('section_80d', models.DecimalField(decimal_places=2, default=0.0, help_text='Medical Insurance', max_digits=10)),
                ('hra_rent_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_declarations', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='employees.employee')),
            ],
        ),
    ]
