# Generated by Django 6.0.1 on 2026-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('employees', '0006_employee_address_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime')], max_length=10)),
                ('financial_year', models.CharField(help_text='e.g. 2023-2024', max_length=9)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for infinite (highest slab)', max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('cess_percent', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='regime',
            field=models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime')], default='OLD', max_length=10),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='total_declared_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='verified_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='taxdeclaration',
            unique_together={('employee', 'financial_year')},
        ),
    ]
