# Generated by Django 6.0.1 on 2026-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_address_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ctc',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual Cost to Company', max_digits=12),
        ),
    ]
