# Generated by Django 6.0.1 on 2026-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
