# Generated by Django 6.0.1 on 2026-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='secondary_departments',
            field=models.ManyToManyField(blank=True, related_name='secondary_employees', to='employees.department'),
        ),
    ]
