# Generated by Django 5.1.9 on 2026-02-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_designation_estimated_max_ctc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='estimated_max_ctc',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='estimated_min_ctc',
        ),
    ]
