# Generated by Django 5.1.9 on 2026-02-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_profileupdaterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUpdateRequest',
        ),
    ]
