# Generated by Django 6.0.1 on 2026-01-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='salary_cycle_start_day',
            field=models.PositiveIntegerField(default=1, help_text='Day of month when cycle starts'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_slabs',
            field=models.JSONField(blank=True, default=dict, help_text='JSON structure for tax slabs'),
        ),
    ]
