# Generated by Django 5.1.9 on 2026-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abbreviation for sidebar/mobile', max_length=50),
        ),
    ]
