# Generated by Django 5.1.9 on 2026-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='geofence_radius',
            field=models.PositiveIntegerField(default=200, help_text='Allowed radius in meters'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='College center latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='College center longitude', max_digits=9, null=True),
        ),
    ]
