# Generated by Django 5.1.9 on 2026-03-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('PAYROLL', 'Payroll Issue'), ('IT', 'IT Support'), ('HR', 'HR Query'), ('PROFILE_UPDATE', 'Profile Update Request'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
