# Generated by Django 6.0.1 on 2026-01-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_department_employee_department_designation_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The payroll month this applies to')),
                ('type', models.CharField(choices=[('OVERTIME', 'Overtime'), ('ARREARS', 'Arrears'), ('BONUS', 'Bonus'), ('INCENTIVE', 'Incentive'), ('DEDUCTION', 'Adhoc Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='employees.employee')),
            ],
        ),
    ]
