# Generated by Django 6.0.1 on 2026-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrolladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollledger',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollledger',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
