# Generated by Django 6.0.1 on 2026-01-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollledger_payment_date_payrollledger_utr_number'),
        ('tenants', '0002_tenant_salary_cycle_start_day_tenant_tax_slabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollledger',
            name='calculations_breakdown',
            field=models.JSONField(blank=True, help_text='Full breakdown of earnings/deductions', null=True),
        ),
        migrations.AddField(
            model_name='payrollledger',
            name='esi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollledger',
            name='pf_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollledger',
            name='pt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollledger',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollledger',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollledger',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HELD', 'Held'), ('LOCKED', 'Locked'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollledger',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollledger',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SalaryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_templates', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('formula', models.TextField(blank=True, help_text='Override component formula if needed', null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='payroll.salarytemplate')),
            ],
            options={
                'unique_together': {('template', 'component')},
            },
        ),
    ]
