# Generated by Django 6.0.1 on 2026-01-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_address_employee_blood_group_and_more'),
        ('payroll', '0004_payrollledger_calculations_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Principal Loan Amount', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual Interest Rate %', max_digits=5)),
                ('tenure_months', models.IntegerField(help_text='Number of EMIs')),
                ('monthly_emi', models.DecimalField(decimal_places=2, help_text='Calculated EMI', max_digits=12)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active (Repaying)'), ('CLOSED', 'Closed (Fully Repaid)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='payroll.loan')),
                ('payroll_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='payroll.payrollledger')),
            ],
        ),
    ]
