# Generated by Django 6.0.1 on 2026-01-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_address_employee_blood_group_and_more'),
        ('payroll', '0005_loan_loanrepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title', models.CharField(help_text='Expense Title', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_expense', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reimbursements/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Unpaid)'), ('REJECTED', 'Rejected'), ('PAID', 'Paid (Processed)')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='employees.employee')),
                ('payroll_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='payroll.payrollledger')),
            ],
        ),
    ]
