# Generated by Django 6.0.1 on 2026-01-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolladjustment',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if created by system logic (e.g. Overtime)'),
        ),
    ]
