# Generated by Django 6.0.1 on 2026-03-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_id_alter_leavebalance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_image_check_in',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_image_check_out',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
